[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sefar = {path = "./sefar"}
csv = "1.1.6"
#serde_derive ="1.0.130"
serde = { version = "1.0", features = ["derive"]}